name: Main

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */1 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Run Script
        run: node index.js
        env:
          API_KEY: ${{secrets.API_KEY}}
          WEBHOOK_URL: ${{secrets.WEBHOOK_URL}}
      
      - name: Commit previous_ids.json
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add previous_ids.json
          git diff --cached --quiet || git commit -m 'Update previous_ids.json'
          git push
